version: "3.8"

services:
  mailer:
    build: .
    container_name: mailer

    ports:
      - "80:80"

    env_file:
      - .env

    volumes:
      - ./recipients.txt:/app/recipients.txt
      - ./suppression.json:/app/suppression.json

    restart: unless-stopped